version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - react-app-1
      - react-app-2
      - express-server

  react-app-1:
    build: ./react-app-1
    container_name: react-app-1
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  react-app-2:
    build: ./react-app-2
    container_name: react-app-2
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  express-server:
    build: ./express-server
    container_name: express-server
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
