services:
  client:
    build:
      context: ./client
      args:
      - PUBLIC_URL=/client
    networks:
      - test

  web:
      build:
        context: ./web
        args:
        - PUBLIC_URL=/
      networks:
        - test

  server:
    build: ./server
    container_name: server
    restart: always
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=production
      - PORT=5000
    ports:
      - "5000:5000"

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - 80:80
    networks:
      - test
    depends_on:
      - web
      - client
      - server

networks:
  test: