services:
  client:
    build:
      context: ./client
      args:
      - PUBLIC_URL=/client
    networks:
      - test

  web:
      build:
        context: ./web
        args:
        - PUBLIC_URL=/
      networks:
        - test

  nginx:
    build:
      context: ./nginx
    ports:
      - 3000:80
    networks:
      - test
    depends_on:
      - web
      - client

networks:
  test: